name: CI/CD Demo Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Project
        run: |
          echo "Building project..."
          sleep 5
          echo "Build complete."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Tests
        run: |
          echo "Running tests..."
          sleep 10
          echo "Tests passed."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          sleep 5
          echo "Deployment successful! Welcome to AutoFlow."